# Generated by Django 4.0.1 on 2022-01-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contarct',
            new_name='Contract',
        ),
    ]
