# Generated by Django 4.0.1 on 2022-01-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_unlimitjismoniy'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlimitjismoniy',
            name='payment_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='unlimitjismoniy',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
