# Generated by Django 4.0.1 on 2022-01-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_unlimitjismoniy_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlimitjismoniy',
            name='applicant',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlimitjismoniy',
            name='insuranceFormUuid',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='unlimitjismoniy',
            name='policy_number',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='unlimitjismoniy',
            name='policy_seria',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
