# Generated by Django 4.0.1 on 2022-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_unlimitjismoniy_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlimitjismoniy',
            name='transaction_state',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
