# Generated by Django 4.0.1 on 2022-01-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_unlimitjismoniy_transaction_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlimitjismoniy',
            name='policy_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
