# Generated by Django 4.0.2 on 2022-03-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_alter_contractjson_options_contractjson_csrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractjson',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
