# Generated by Django 4.0.2 on 2022-03-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_contractjson_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractjson',
            name='payme_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
