# Generated by Django 4.0.2 on 2022-03-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_contractjson_payme_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractjson',
            name='transaction_order_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contractjson',
            name='transaction_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractjson',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
