# Generated by Django 4.0.2 on 2022-03-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_contractjson_transaction_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractjson',
            old_name='transaction_order_id',
            new_name='transaction_order_key',
        ),
    ]
