version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/mediafiles
    entrypoint:
      - ./entrypoint.sh

  nginx:
    build: ./nginx

    volumes:
     - static_volume:/home/app/web/static
     - media_volume:/home/app/web/mediafiles
    ports:
      - 1338:80
    depends_on:
      - web
      
volumes:
  static_volume:
  media_volume: